"""initial schema

Revision ID: e25ff6e58bbc
Revises: 
Create Date: 2026-08-02 02:47:20.890611
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

revision = 'e25ff6e58bbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('parent_run_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('agent_type', sa.String(length=40), nullable=False),
    sa.Column('policy_version', sa.String(length=20), nullable=False),
    sa.Column('prompt_template_version', sa.String(length=20), nullable=False),
    sa.Column('prompt_checksum', sa.String(length=72), nullable=False),
    sa.Column('model_profile', sa.JSON(), nullable=False),
    sa.Column('tool_grants', sa.JSON(), nullable=False),
    sa.Column('budget', sa.JSON(), nullable=False),
    sa.Column('input_artifacts', sa.JSON(), nullable=False),
    sa.Column('output_artifacts', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_rub', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('data_class', sa.String(length=20), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_parent_run_id'), ['parent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=60), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('required_role', sa.String(length=40), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('delegated_to', sa.String(length=64), nullable=True),
    sa.Column('policy_version', sa.String(length=20), nullable=False),
    sa.Column('subject_checksum', sa.String(length=72), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_subject_type'), ['subject_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('uri', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=72), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('data_class', sa.String(length=20), nullable=False),
    sa.Column('producer_run_id', sa.String(length=64), nullable=True),
    sa.Column('producer_kind', sa.String(length=40), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_producer_run_id'), ['producer_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=72), nullable=False),
    sa.Column('hash', sa.String(length=72), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_seq'), ['seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('limit_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('spent_amount', sa.Float(), nullable=False),
    sa.Column('soft_pct', sa.Integer(), nullable=False),
    sa.Column('warning_pct', sa.Integer(), nullable=False),
    sa.Column('hard_stopped', sa.Boolean(), nullable=False),
    sa.Column('notified_thresholds', sa.JSON(), nullable=False),
    sa.Column('override_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_amount', sa.Float(), nullable=False),
    sa.Column('override_by', sa.String(length=64), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uq_budget_project')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('change_sets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('repository_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('branch', sa.String(length=200), nullable=False),
    sa.Column('base_branch', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('diff', sa.Text(), nullable=False),
    sa.Column('files_changed', sa.JSON(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_url', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_sets_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_sets_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_sets_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_sets_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_sets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cost_ledger_entries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('effective_rate', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('invoice_ref', sa.String(length=120), nullable=False),
    sa.Column('billable', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_ledger_entries_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_ledger_entries_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_ledger_entries_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_ledger_entries_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_ledger_entries_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('deployments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('environment_id', sa.String(length=64), nullable=False),
    sa.Column('release_id', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('approval_ids', sa.JSON(), nullable=False),
    sa.Column('health', sa.JSON(), nullable=False),
    sa.Column('rollback_of_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployments_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_release_id'), ['release_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('environments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('config_version', sa.String(length=40), nullable=False),
    sa.Column('secret_refs', sa.JSON(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('current_release_id', sa.String(length=64), nullable=True),
    sa.Column('previous_release_id', sa.String(length=64), nullable=True),
    sa.Column('drift_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_env_name')
    )
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environments_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_environments_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=72), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', 'endpoint', name='uq_idem_key')
    )
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_keys_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('deployment_id', sa.String(length=64), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('postmortem_url', sa.String(length=400), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('leased_by', sa.String(length=80), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_job_dedupe')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_run_after'), ['run_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('license_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('component', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=60), nullable=False),
    sa.Column('license_id', sa.String(length=80), nullable=False),
    sa.Column('policy', sa.String(length=20), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('scope', sa.String(length=200), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('license_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_license_records_license_id'), ['license_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_license_records_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_license_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('notification_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=300), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('operations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('causation_id', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('dead_lettered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_type'), ['type'], unique=False)

    op.create_table('policy_waivers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('gate', sa.String(length=40), nullable=False),
    sa.Column('finding_key', sa.String(length=200), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('issued_by', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_waivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_waivers_gate'), ['gate'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_waivers_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_waivers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('processed_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('consumer', sa.String(length=80), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consumer', 'event_id', name='uq_processed_event')
    )
    with op.batch_alter_table('processed_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_events_consumer'), ['consumer'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_events_event_id'), ['event_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('golden_path', sa.String(length=60), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=True),
    sa.Column('manager_user_id', sa.String(length=64), nullable=True),
    sa.Column('data_class', sa.String(length=20), nullable=False),
    sa.Column('budget_rub', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('repository_id', sa.String(length=64), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('quality_gate_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=40), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('gate', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('waiver_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_gate_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_gate_results_gate'), ['gate'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_gate_results_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_gate_results_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_gate_results_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('releases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('artifact_digest', sa.String(length=80), nullable=False),
    sa.Column('change_set_ids', sa.JSON(), nullable=False),
    sa.Column('evidence_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('sbom_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('release_notes', sa.Text(), nullable=False),
    sa.Column('rollback_plan', sa.Text(), nullable=False),
    sa.Column('migration_plan', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('verdict', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_release_version')
    )
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_releases_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_releases_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('repositories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('default_branch', sa.String(length=80), nullable=False),
    sa.Column('protected_branches', sa.JSON(), nullable=False),
    sa.Column('code_owners', sa.JSON(), nullable=False),
    sa.Column('required_checks', sa.JSON(), nullable=False),
    sa.Column('template', sa.String(length=80), nullable=False),
    sa.Column('clone_url', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repositories_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repositories_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('runner_workspaces',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('driver', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('container_id', sa.String(length=120), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runner_workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runner_workspaces_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runner_workspaces_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runner_workspaces_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('plan', sa.String(length=40), nullable=False),
    sa.Column('data_region', sa.String(length=40), nullable=False),
    sa.Column('max_external_data_class', sa.String(length=20), nullable=False),
    sa.Column('quotas', sa.JSON(), nullable=False),
    sa.Column('policy_set', sa.JSON(), nullable=False),
    sa.Column('monthly_budget_rub', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('event_types', sa.JSON(), nullable=False),
    sa.Column('secret', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_subscriptions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_subscriptions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('blueprint_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('brief_version_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('architecture', sa.JSON(), nullable=False),
    sa.Column('backlog', sa.JSON(), nullable=False),
    sa.Column('nfr', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('estimate', sa.JSON(), nullable=False),
    sa.Column('adr_refs', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=72), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('produced_by_run_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_blueprint_version')
    )
    with op.batch_alter_table('blueprint_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blueprint_versions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blueprint_versions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('brief_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('completeness', sa.Integer(), nullable=False),
    sa.Column('open_questions', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=72), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_brief_version')
    )
    with op.batch_alter_table('brief_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brief_versions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brief_versions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('blueprint_version_id', sa.String(length=64), nullable=True),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('executor', sa.String(length=20), nullable=False),
    sa.Column('agent_type', sa.String(length=40), nullable=True),
    sa.Column('assignee_user_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=False),
    sa.Column('estimate_tokens', sa.Integer(), nullable=False),
    sa.Column('estimate_hours', sa.Float(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_service_account', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('api_tokens',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('role_bindings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', 'project_id', name='uq_binding_scope')
    )
    with op.batch_alter_table('role_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_bindings_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_bindings_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_bindings_user_id'), ['user_id'], unique=False)

    op.create_table('task_dependencies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('depends_on_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_id', name='uq_task_edge')
    )
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_dependencies_depends_on_id'), ['depends_on_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dependencies_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_dependencies_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_dependencies_depends_on_id'))

    op.drop_table('task_dependencies')
    with op.batch_alter_table('role_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_bindings_user_id'))
        batch_op.drop_index(batch_op.f('ix_role_bindings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_role_bindings_project_id'))

    op.drop_table('role_bindings')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_tenant_id'))

    op.drop_table('api_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('brief_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brief_versions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_brief_versions_project_id'))

    op.drop_table('brief_versions')
    with op.batch_alter_table('blueprint_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blueprint_versions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_blueprint_versions_project_id'))

    op.drop_table('blueprint_versions')
    with op.batch_alter_table('webhook_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_subscriptions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_subscriptions_project_id'))

    op.drop_table('webhook_subscriptions')
    op.drop_table('tenants')
    with op.batch_alter_table('runner_workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runner_workspaces_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_runner_workspaces_run_id'))
        batch_op.drop_index(batch_op.f('ix_runner_workspaces_project_id'))

    op.drop_table('runner_workspaces')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repositories_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_repositories_project_id'))

    op.drop_table('repositories')
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_releases_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_releases_project_id'))

    op.drop_table('releases')
    with op.batch_alter_table('quality_gate_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_gate_results_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_quality_gate_results_subject_id'))
        batch_op.drop_index(batch_op.f('ix_quality_gate_results_project_id'))
        batch_op.drop_index(batch_op.f('ix_quality_gate_results_gate'))

    op.drop_table('quality_gate_results')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_projects_state'))
        batch_op.drop_index(batch_op.f('ix_projects_owner_user_id'))

    op.drop_table('projects')
    with op.batch_alter_table('processed_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_events_event_id'))
        batch_op.drop_index(batch_op.f('ix_processed_events_consumer'))

    op.drop_table('processed_events')
    with op.batch_alter_table('policy_waivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_waivers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_policy_waivers_project_id'))
        batch_op.drop_index(batch_op.f('ix_policy_waivers_gate'))

    op.drop_table('policy_waivers')
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_events_type'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_published_at'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_correlation_id'))

    op.drop_table('outbox_events')
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_operations_project_id'))

    op.drop_table('operations')
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_project_id'))

    op.drop_table('notification_logs')
    with op.batch_alter_table('license_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_license_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_license_records_project_id'))
        batch_op.drop_index(batch_op.f('ix_license_records_license_id'))

    op.drop_table('license_records')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_run_after'))
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))

    op.drop_table('jobs')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_incidents_project_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_tenant_id'))

    op.drop_table('idempotency_keys')
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_environments_project_id'))

    op.drop_table('environments')
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_status'))
        batch_op.drop_index(batch_op.f('ix_deployments_release_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_project_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_environment_id'))

    op.drop_table('deployments')
    with op.batch_alter_table('cost_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_ledger_entries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cost_ledger_entries_stage'))
        batch_op.drop_index(batch_op.f('ix_cost_ledger_entries_run_id'))
        batch_op.drop_index(batch_op.f('ix_cost_ledger_entries_project_id'))
        batch_op.drop_index(batch_op.f('ix_cost_ledger_entries_occurred_at'))

    op.drop_table('cost_ledger_entries')
    with op.batch_alter_table('change_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_sets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_change_sets_task_id'))
        batch_op.drop_index(batch_op.f('ix_change_sets_run_id'))
        batch_op.drop_index(batch_op.f('ix_change_sets_repository_id'))
        batch_op.drop_index(batch_op.f('ix_change_sets_project_id'))

    op.drop_table('change_sets')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_budgets_project_id'))

    op.drop_table('budgets')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_seq'))
        batch_op.drop_index(batch_op.f('ix_audit_events_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_project_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_producer_run_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_subject_type'))
        batch_op.drop_index(batch_op.f('ix_approvals_subject_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_approvals_project_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_task_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_status'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_parent_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_correlation_id'))

    op.drop_table('agent_runs')
    # ### end Alembic commands ###
