"""telegram bot interface

Revision ID: fba2efcc2d0f
Revises: e25ff6e58bbc
Create Date: 2026-08-02 05:49:54.741142
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

revision = 'fba2efcc2d0f'
down_revision = 'e25ff6e58bbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_chats',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('state_data', sa.JSON(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unlinked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', name='uq_telegram_chat')
    )
    with op.batch_alter_table('telegram_chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_chats_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_chats_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_chats_user_id'), ['user_id'], unique=False)

    op.create_table('telegram_link_codes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_chat_id', sa.String(length=64), nullable=False),
    sa.Column('issued_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_telegram_link_code')
    )
    with op.batch_alter_table('telegram_link_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_link_codes_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_link_codes_user_id'), ['user_id'], unique=False)

    op.create_table('telegram_update_cursor',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('last_update_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_update_cursor')
    with op.batch_alter_table('telegram_link_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_link_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_telegram_link_codes_tenant_id'))

    op.drop_table('telegram_link_codes')
    with op.batch_alter_table('telegram_chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_chats_user_id'))
        batch_op.drop_index(batch_op.f('ix_telegram_chats_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_telegram_chats_chat_id'))

    op.drop_table('telegram_chats')
    # ### end Alembic commands ###
